name: Validate Logic Profile

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch

jobs:
  reason-ontology:
    runs-on: ubuntu-latest  # Required base runner
    container:
      image: obolibrary/robot:latest  # Use the ROBOT Docker image directly

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Download repository files into the container

      - name: Run ROBOT Reasoning
        run: |
          robot reason \
            --catalog "catalog-v001.xml" \
            --input "cco-d-acts.ttl" \
            --output "inferred-cco-d-acts.ttl" -vvv

      - name: Save Output
        run: |
          mkdir -p output
          mv inferred-cco-d-acts.ttl output/
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inferred-ontology
          path: output/inferred-cco-d-acts.ttl

  ontology-validate-dl:
    runs-on: ubuntu-latest
    container: obolibrary/robot:latest
    outputs:
      validation-status: ${{ steps.validate-dl.outcome }}  # Pass step outcome as a job output

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ontology DL profile validation
        id: validate-dl  # Assign ID to the step
        continue-on-error: true  # Allow this step to continue even if it fails
        run: |
          robot validate-profile \
            --profile DL \
            --catalog "catalog-v001.xml" \
            --input "cco-d-acts.ttl" \
            --output "cco-d-acts-dl-validation.txt" -vvv

      - name: Upload Validation Results
        uses: actions/upload-artifact@v4
        with:
          name: dl-validation-results
          path: cco-d-acts-dl-validation.txt

  ontology-validate-full:
    runs-on: ubuntu-latest
    needs: ontology-validate-dl
    if: needs.ontology-validate-dl.outputs.validation-status == 'failure'  # Run only if the previous job failed
    container:
      image: obolibrary/robot:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ontology Full profile validation
        run: |
          robot validate-profile \
            --profile Full \
            --catalog "catalog-v001.xml" \
            --input "cco-d-acts.ttl" \
            --output "cco-d-acts-full-validation.txt" -vvv

      - name: Upload Validation Results
        uses: actions/upload-artifact@v4
        with:
          name: full-validation-results
          path: cco-d-acts-full-validation.txt